/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIInvetario;

import Clases.Registrar_Producto;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author Roberto
 */
public class RegistrarProducto extends javax.swing.JInternalFrame {
    public static LinkedList contenedor = new LinkedList();
    public int Encontrado;
    /**
     * Creates new form Producto
     */
    public RegistrarProducto() {
        initComponents();
        
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton2 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_Ayuda_Ventana_Producto = new javax.swing.JButton();
        jButton_Guardar_Producto = new javax.swing.JButton();
        jTextField_Codigo_EAN_RegistrarProducto = new javax.swing.JTextField();
        jTextField_Nombre_Corto_RegistrarProducto = new javax.swing.JTextField();
        jTextField_Nombre_Largo_RegistrarProducto = new javax.swing.JTextField();
        jTextField_Descripcion_RegistrarProducto = new javax.swing.JTextField();
        jTextField_Precio_Venta_RegistrarProducto = new javax.swing.JTextField();
        jTextField_Precio_Compra_RegistrarProducto = new javax.swing.JTextField();
        jTextField_Largo_RegistrarProducto = new javax.swing.JTextField();
        jTextField_Ancho_RegistrarProducto = new javax.swing.JTextField();
        jTextField_Alto_RegistrarProducto = new javax.swing.JTextField();
        jTextField_Stock_RegistrarProducto = new javax.swing.JTextField();
        jTextField_Categoria_RegistrarProducto = new javax.swing.JTextField();
        jTextField_Fecha_De_Vencimiento_RegistrarProducto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jToggleButton2.setText("Ayuda");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nomb. Largo", "Nomb. Corto", "Stock", "descripción", "EAN", "Largo", "Ancho", "Alto", "Precio Compra", "Precio de Venta", "F. de Vencimiento", "Categoria"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("EAN:");

        jLabel3.setText("Nombre Corto:");

        jLabel4.setText("Nombre Largo:");

        jLabel5.setText("    Descripción: ");

        jLabel6.setText("   Largo:");

        jLabel7.setText("Ancho:");

        jLabel8.setText("   Alto:");

        jLabel9.setText("    Categorias:");

        jLabel10.setText("Precio Compra:");

        jLabel11.setText("Precio Venta:");

        jLabel12.setText("F. de Vencimiento:");

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jLabel1.setText(" Stock:");

        jButton_Ayuda_Ventana_Producto.setText("AYUDA");
        jButton_Ayuda_Ventana_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Ayuda_Ventana_ProductoActionPerformed(evt);
            }
        });

        jButton_Guardar_Producto.setText("Guardar");
        jButton_Guardar_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Guardar_ProductoActionPerformed(evt);
            }
        });

        jButton1.setText("Registro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_Codigo_EAN_RegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Largo_RegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_Precio_Compra_RegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_Nombre_Corto_RegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_Nombre_Largo_RegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField_Descripcion_RegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                                        .addComponent(jButton_Ayuda_Ventana_Producto))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField_Precio_Venta_RegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField_Ancho_RegistrarProducto)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(105, 105, 105)
                                                .addComponent(jLabel12))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jTextField_Alto_RegistrarProducto)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel10)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField_Stock_RegistrarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                            .addComponent(jTextField_Categoria_RegistrarProducto))
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_Fecha_De_Vencimiento_RegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_Guardar_Producto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_Codigo_EAN_RegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Nombre_Corto_RegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Nombre_Largo_RegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Descripcion_RegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_Ayuda_Ventana_Producto)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_Precio_Venta_RegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Precio_Compra_RegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Largo_RegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_Ancho_RegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jTextField_Alto_RegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Stock_RegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Fecha_De_Vencimiento_RegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_Categoria_RegistrarProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Guardar_Producto)
                    .addComponent(jButton1))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
       dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void jButton_Ayuda_Ventana_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Ayuda_Ventana_ProductoActionPerformed
       
    }//GEN-LAST:event_jButton_Ayuda_Ventana_ProductoActionPerformed

    private void jButton_Guardar_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Guardar_ProductoActionPerformed

        if (jTextField_Codigo_EAN_RegistrarProducto.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un Codigo.");
            jTextField_Codigo_EAN_RegistrarProducto.requestFocus();
            return;
        }

        if (jTextField_Nombre_Corto_RegistrarProducto.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un Nombre Corto al producto.");
            jTextField_Nombre_Corto_RegistrarProducto.requestFocus();
            return;
        }
        if (jTextField_Nombre_Largo_RegistrarProducto.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar Nombre Largo.");
            jTextField_Nombre_Largo_RegistrarProducto.requestFocus();
            return;
        }

        if (jTextField_Descripcion_RegistrarProducto.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar una Descripcion.");
            jTextField_Descripcion_RegistrarProducto.requestFocus();
            return;
        }

        if (jTextField_Precio_Venta_RegistrarProducto.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar Precio Venta.");
            jTextField_Precio_Venta_RegistrarProducto.requestFocus();
            return;
        }

        if (jTextField_Precio_Compra_RegistrarProducto.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar Precio Compra.");
            jTextField_Precio_Compra_RegistrarProducto.requestFocus();
            return;
        }

        if (jTextField_Largo_RegistrarProducto.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar Largo del Producto.");
            jTextField_Largo_RegistrarProducto.requestFocus();
            return;
        }
        if (jTextField_Ancho_RegistrarProducto.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar Ancho del Prodcuto.");
            jTextField_Ancho_RegistrarProducto.requestFocus();
            return;
        }
        if (jTextField_Alto_RegistrarProducto.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar Alto Del Producto.");
            jTextField_Alto_RegistrarProducto.requestFocus();
            return;
        }
        if (jTextField_Stock_RegistrarProducto.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar Stock.");
            jTextField_Stock_RegistrarProducto.requestFocus();
            return;
        }

          if (jTextField_Categoria_RegistrarProducto.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingrese una categoria.");
            jTextField_Categoria_RegistrarProducto.requestFocus();
            return;
        }

        if (jTextField_Fecha_De_Vencimiento_RegistrarProducto.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar Fecha de vencimiento.");
            jTextField_Fecha_De_Vencimiento_RegistrarProducto.requestFocus();
            return;
        } else {
            JOptionPane.showMessageDialog(null, "Agregado con Exito.");

        }

        String codigo_ean = jTextField_Codigo_EAN_RegistrarProducto.getText();
        String nombre_corto = jTextField_Nombre_Corto_RegistrarProducto.getText();
        String nombre_largo = jTextField_Nombre_Largo_RegistrarProducto.getText();
        String descripcion = jTextField_Descripcion_RegistrarProducto.getText();
        String precio_venta = jTextField_Precio_Venta_RegistrarProducto.getText();
        String precio_compra = jTextField_Precio_Compra_RegistrarProducto.getText();
        String largo = jTextField_Largo_RegistrarProducto.getText();
        String ancho = jTextField_Ancho_RegistrarProducto.getText();
        String alto = jTextField_Alto_RegistrarProducto.getText();
        String stock = jTextField_Stock_RegistrarProducto.getText();
        String categoria = jTextField_Categoria_RegistrarProducto.getText();
        String fecha_de_vencimiento = jTextField_Fecha_De_Vencimiento_RegistrarProducto.getText();

        Registrar_Producto clase = new Registrar_Producto(codigo_ean, nombre_largo, nombre_corto,descripcion,precio_venta,precio_compra,largo,ancho,alto,stock,categoria,fecha_de_vencimiento);
        contenedor.add(clase);

        jTextField_Codigo_EAN_RegistrarProducto.setText("");
        jTextField_Nombre_Corto_RegistrarProducto.setText("");
        jTextField_Nombre_Largo_RegistrarProducto.setText("");
        jTextField_Descripcion_RegistrarProducto.setText("");
        jTextField_Precio_Venta_RegistrarProducto.setText("");
        jTextField_Precio_Compra_RegistrarProducto.setText("");
        jTextField_Largo_RegistrarProducto.setText("");
        jTextField_Ancho_RegistrarProducto.setText("");
        jTextField_Alto_RegistrarProducto.setText("");
        jTextField_Stock_RegistrarProducto.setText("");
        jTextField_Categoria_RegistrarProducto.setText("");
        jTextField_Fecha_De_Vencimiento_RegistrarProducto.setText("");
        //Vaciar textfields

    }//GEN-LAST:event_jButton_Guardar_ProductoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Tabla_Productos l = new Tabla_Productos();
        l.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Ayuda_Ventana_Producto;
    private javax.swing.JButton jButton_Guardar_Producto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_Alto_RegistrarProducto;
    private javax.swing.JTextField jTextField_Ancho_RegistrarProducto;
    private javax.swing.JTextField jTextField_Categoria_RegistrarProducto;
    private javax.swing.JTextField jTextField_Codigo_EAN_RegistrarProducto;
    private javax.swing.JTextField jTextField_Descripcion_RegistrarProducto;
    private javax.swing.JTextField jTextField_Fecha_De_Vencimiento_RegistrarProducto;
    private javax.swing.JTextField jTextField_Largo_RegistrarProducto;
    private javax.swing.JTextField jTextField_Nombre_Corto_RegistrarProducto;
    private javax.swing.JTextField jTextField_Nombre_Largo_RegistrarProducto;
    private javax.swing.JTextField jTextField_Precio_Compra_RegistrarProducto;
    private javax.swing.JTextField jTextField_Precio_Venta_RegistrarProducto;
    private javax.swing.JTextField jTextField_Stock_RegistrarProducto;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables


}
