/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIInvetario;

import Clases.Registrar_Usuario;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author
 */
public class Tabla_Usuario extends javax.swing.JFrame {
    
    private DefaultTableModel model;
    int con = 0;

    /**
     * Creates new form Tabla_Producto
     */
    public Tabla_Usuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        GuardarUsuario();
        HistorialUsuario();
        
    }
    
        public void GuardarUsuario(){
    
        String data[][]={};
        String col[] = {"NOMBRE USUARIO","NOMBRE COMPLETO","RUT","CORREO","CONTRASEÑA","CONFIRMAR CONTRASEÑA","ID BODEGA","CARGO"};
        model = new DefaultTableModel(data, col);
        jTable_Tabla_Usuario.setModel(model);
        
    }
    
    public void HistorialUsuario(){
    
        Registrar_Usuario p;
        for(int i=0; i<RegistrarUsuario.contenedor.size(); i++){
        
            p = (Registrar_Usuario) RegistrarUsuario.contenedor.get(i);
            model.insertRow(con, new Object[]{});
            model.setValueAt(p.getNombre_usuario(), con, 0);
            model.setValueAt(p.getNombre_completo(), con, 1);
            model.setValueAt(p.getRut(), con, 2);
            model.setValueAt(p.getCorreo(), con, 3);
            model.setValueAt(p.getContraseña(), con, 4);
            model.setValueAt(p.getConfirmar_contraseña(), con, 5);
            model.setValueAt(p.getId_bodega(), con,6 );
            model.setValueAt(p.getCargo(), con, 7);
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Producto_Registrados_Tabla_Registrarproducto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Tabla_Usuario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Producto_Registrados_Tabla_Registrarproducto.setBackground(new java.awt.Color(0, 51, 153));
        jLabel_Producto_Registrados_Tabla_Registrarproducto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Producto_Registrados_Tabla_Registrarproducto.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Producto_Registrados_Tabla_Registrarproducto.setText("Usuario registrados");
        getContentPane().add(jLabel_Producto_Registrados_Tabla_Registrarproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        jTable_Tabla_Usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable_Tabla_Usuario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 1300, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabla_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabla_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabla_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabla_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabla_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Producto_Registrados_Tabla_Registrarproducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Tabla_Usuario;
    // End of variables declaration//GEN-END:variables
}
